SET IDENTITY_INSERT [dbo].[Verbe] ON
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (1, N'abide', N'abode', N'abode', N'demeurer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (2, N'arise', N'arisen', N'arose', N's''élever, survenir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (3, N'awake', N'awoken', N'awoke', N'(se) réveiller')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (4, N'bear', N'borne', N'bore', N'supporter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (5, N'beat', N'beaten', N'beat', N'battre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (6, N'become', N'become', N'became', N'devenir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (7, N'begin', N'begun', N'began', N'commencer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (8, N'bend', N'bent', N'bent', N'(se) courber')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (9, N'bet', N'bet', N'bet', N'parier')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (10, N'bid', N'bid', N'bid', N'offrir (un prix)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (11, N'bind', N'bound', N'bound', N'lier, relier')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (12, N'bite', N'bitten', N'bit', N'mordre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (13, N'bleed', N'bled', N'bled', N'saigner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (14, N'blow', N'blown', N'blew', N'souffler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (15, N'break', N'broken', N'broke', N'casser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (16, N'breed', N'bred', N'bred', N'élever (du bétail)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (17, N'bring', N'brought', N'brought', N'apporter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (18, N'build', N'built', N'built', N'construire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (19, N'burn', N'burnt', N'burnt', N'brûler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (20, N'burst', N'burst', N'burst', N'éclater')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (21, N'buy', N'bought', N'bought', N'acheter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (22, N'cast', N'cast', N'cast', N'jeter, lancer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (23, N'catch', N'caught', N'caught', N'attraper')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (24, N'choose', N'chosen', N'chose', N'choisir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (25, N'cling', N'clung', N'clung', N's''accrocher')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (26, N'come', N'come', N'came', N'venir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (27, N'cost', N'cost', N'cost', N'coûter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (28, N'creep', N'crept', N'crept', N'ramper')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (29, N'cut', N'cut', N'cut', N'couper')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (30, N'deal', N'dealt', N'dealt', N'distribuer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (31, N'dig', N'dug', N'dug', N'creuser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (32, N'do', N'done', N'did', N'faire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (33, N'draw', N'drawn', N'drew', N'dessiner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (34, N'dream', N'dreamt', N'dreamt', N'rêver')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (35, N'drink', N'drunk', N'drank', N'boire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (36, N'drive', N'driven', N'drove', N'conduire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (37, N'dwell', N'dwelt', N'dwelt', N'habiter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (38, N'eat', N'eaten', N'ate', N'manger')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (39, N'fall', N'fallen', N'fell', N'tomber')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (40, N'feed', N'fed', N'fed', N'nourrir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (41, N'feel', N'felt', N'felt', N'sentir, éprouver')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (42, N'fight', N'fought', N'fought', N'combattre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (43, N'find', N'found', N'found', N'trouver')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (44, N'flee', N'fled', N'fled', N's''enfuir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (45, N'fling', N'flung', N'flung', N'jeter violemment')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (46, N'fly', N'flown', N'flew', N'voler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (47, N'forbid', N'forbidden', N'forbade', N'interdire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (48, N'forget', N'forgotten', N'forgot', N'oublier')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (49, N'forgive', N'forgiven', N'forgave', N'pardonner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (50, N'freeze', N'frozen', N'froze', N'geler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (51, N'get', N'got', N'got', N'obtenir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (52, N'give', N'given', N'gave', N'donner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (53, N'go', N'gone', N'went', N'aller')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (54, N'grind', N'ground', N'ground', N'moudre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (55, N'grow', N'grown', N'grew', N'grandir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (56, N'hang', N'hung', N'hung', N'pendre, accrocher')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (57, N'have', N'had', N'had', N'avoir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (58, N'hear', N'heard', N'heard', N'entendre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (59, N'hide', N'hidden', N'hid', N'(se) cacher')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (60, N'hit', N'hit', N'hit', N'frapper, atteindre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (61, N'hold', N'held', N'held', N'tenir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (62, N'hurt', N'hurt', N'hurt', N'blesser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (63, N'keep', N'kept', N'kept', N'garder')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (64, N'kneel', N'knelt', N'knelt', N's''agenouiller')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (65, N'know', N'known', N'knew', N'savoir, connaître')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (66, N'lay', N'laid', N'laid', N'poser à plat')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (67, N'lead', N'led', N'led', N'mener')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (68, N'lean', N'leant', N'leant', N's''appuyer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (69, N'leap', N'leapt', N'leapt', N'sauter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (70, N'learn', N'learnt', N'learnt', N'apprendre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (71, N'leave', N'left', N'left', N'laisser, quitter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (72, N'lend', N'lent', N'lent', N'prêter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (73, N'let', N'let', N'let', N'permettre, louer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (74, N'lie', N'lain', N'lay', N'être étendu')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (75, N'light', N'lit', N'lit', N'allumer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (76, N'lose', N'lost', N'lost', N'perdre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (77, N'make', N'made', N'made', N'faire, fabriquer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (78, N'mean', N'meant', N'meant', N'signifier')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (79, N'meet', N'met', N'met', N'(se) rencontrer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (80, N'mow', N'mown', N'mowed', N'tondre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (81, N'overcome', N'overcome', N'overcame', N'surmonter, vaincre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (82, N'pay', N'paid', N'paid', N'payer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (83, N'put', N'put', N'put', N'mettre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (84, N'quit', N'quit', N'quit', N'cesser (de)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (85, N'read', N'read', N'read', N'lire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (86, N'rid', N'rid', N'rid', N'débarrasser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (87, N'ride', N'ridden', N'rode', N'chevaucher')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (88, N'ring', N'rung', N'rang', N'sonner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (89, N'rise', N'risen', N'rose', N's''élever, se lever')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (90, N'run', N'run', N'ran', N'courir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (91, N'saw', N'sawn', N'sawed', N'scier')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (92, N'say', N'said', N'said', N'dire')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (93, N'see', N'seen', N'saw', N'voir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (94, N'seek', N'sought', N'sought', N'chercher')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (95, N'sell', N'sold', N'sold', N'vendre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (96, N'send', N'sent', N'sent', N'envoyer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (97, N'set', N'set', N'set', N'fixer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (98, N'sew', N'sewn', N'sewed', N'coudre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (99, N'shake', N'shaken', N'shook', N'secouer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (100, N'shear', N'shorn', N'sheared', N'tondre (des moutons)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (101, N'shed', N'shed', N'shed', N'verser (des larmes)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (102, N'shine', N'shone', N'shone', N'briller')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (103, N'shoe', N'shod', N'shod', N'ferrer, chausser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (104, N'shoot', N'shot', N'shot', N'tirer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (105, N'show', N'shown', N'showed', N'montrer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (106, N'shrink', N'shrunk', N'shrank', N'rétrécir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (107, N'shut', N'shut', N'shut', N'fermer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (108, N'sing', N'sung', N'sang', N'chanter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (109, N'sink', N'sunk', N'sank', N'couler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (110, N'sit', N'sat', N'sat', N'être assis')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (111, N'sleep', N'slept', N'slept', N'dormir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (112, N'slide', N'slid', N'slid', N'glisser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (113, N'sling', N'slung', N'slung', N'lancer (avec force)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (114, N'slink', N'slunk', N'slunk', N'aller furtivement')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (115, N'slit', N'slit', N'slit', N'fendre, inciser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (116, N'smell', N'smelt', N'smelt', N'sentir (odorat)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (117, N'sow', N'sown', N'sowed', N'semer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (118, N'speak', N'spoken', N'spoke', N'parler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (119, N'speed', N'sped', N'sped', N'aller à toute vitesse')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (120, N'spell', N'spelt', N'spelt', N'épeler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (121, N'spend', N'spent', N'spent', N'dépenser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (122, N'spill', N'spilt', N'spilt', N'renverser (un liquide)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (123, N'spit', N'spat', N'spat', N'cracher')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (124, N'split', N'split', N'split', N'fendre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (125, N'spoil', N'spoilt', N'spoilt', N'gâcher, gâter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (126, N'spread', N'spread', N'spread', N'répandre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (127, N'spring', N'sprung', N'sprang', N'jaillir, bondir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (128, N'stand', N'stood', N'stood', N'être debout')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (129, N'steal', N'stolen', N'stole', N'voler, dérober')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (130, N'stick', N'stuck', N'stuck', N'coller')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (131, N'sting', N'stung', N'stung', N'piquer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (132, N'stink', N'stunk', N'stank', N'puer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (133, N'stride', N'stridden', N'strode', N'marcher à grands pas')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (134, N'strike', N'struck', N'struck', N'frapper')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (135, N'string', N'strung', N'strung', N'enfiler, tendre (une corde)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (136, N'strive', N'striven', N'strove', N's''efforcer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (137, N'swear', N'sworn', N'swore', N'jurer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (138, N'sweep', N'swept', N'swept', N'balayer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (139, N'swell', N'swollen', N'swelled', N'enfler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (140, N'swim', N'swum', N'swam', N'nager')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (141, N'swing', N'swung', N'swung', N'se balancer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (142, N'take', N'taken', N'took', N'prendre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (143, N'teach', N'taught', N'taught', N'enseigner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (144, N'tear', N'torn', N'tore', N'déchirer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (145, N'tell', N'told', N'told', N'dire, raconter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (146, N'think', N'thought', N'thought', N'penser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (147, N'throw', N'thrown', N'threw', N'jeter')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (148, N'thrust', N'thrust', N'thrust', N'enfoncer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (149, N'tread', N'trodden', N'trod', N'fouler aux pieds')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (150, N'undergo', N'undergone', N'underwent', N'subir')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (151, N'understand', N'understood', N'understood', N'comprendre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (152, N'upset', N'upset', N'upset', N'bouleverser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (153, N'wake', N'woken', N'woke', N'(se) réveiller')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (154, N'wear', N'worn', N'wore', N'porter (des vêtements)')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (155, N'weave', N'woven', N'wove', N'tisser')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (156, N'weep', N'wept', N'wept', N'pleurer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (157, N'win', N'won', N'won', N'gagner')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (158, N'wind', N'wound', N'wound', N'enrouler')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (159, N'withdraw', N'withdrawn', N'withdrew', N'(se) retirer')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (160, N'wring', N'wrung', N'wrung', N'tordre')
INSERT INTO [dbo].[Verbe] ([Id], [baseVerbarle], [participePasse], [preterit], [traduction]) VALUES (161, N'write', N'written', N'wrote', N'écrire')
SET IDENTITY_INSERT [dbo].[Verbe] OFF
